---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-mysql-pv
  labels:
    name: drupal-mysql-pv
spec:
  accessModes: [ "ReadWriteOnce" ]
  capacity:
    storage: "5Gi"
  hostPath:
    path: /srv/drupal-mysql-data