---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: drupal-mysql
  name: drupal-mysql-service
spec:
  type: ClusterIP
  selector:
    app: drupal-mysql
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
