---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-mysql-pvc
spec:
  storageClassName: nfs
  accessModes: 
    - ReadWriteMany
  resources:
    requests:
      storage: "5Gi"
  selector:
    matchLabels:
      name: drupal-mysql-pv